version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: diploma-db
    restart: always
    environment:
      POSTGRES_USER: ilya
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: clinic
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ilya -d clinic"]
      interval: 5s
      timeout: 5s
      retries: 10

  auth:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    restart: on-failure
    ports:
      - "50051:50051"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ilya
      DB_PASSWORD: 123
      DB_NAME: clinic
      DB_SSLMODE: disable
      JWT_KEY: ${JWT_KEY}

  admin:
    build:
      context: .
      dockerfile: admin-service/Dockerfile
    restart: on-failure
    ports:
      - "50052:50052"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ilya
      DB_PASSWORD: 123
      DB_NAME: clinic
      DB_SSLMODE: disable
      JWT_KEY: ${JWT_KEY}

  users:
    build:
      context: .
      dockerfile: users-service/Dockerfile
    restart: on-failure
    ports:
      - "50053:50053"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ilya
      DB_PASSWORD: 123
      DB_NAME: clinic
      DB_SSLMODE: disable
      JWT_KEY: ${JWT_KEY}

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - auth
      - admin
      - users
    environment:
      JWT_KEY: ${JWT_KEY}

volumes:
  postgres_data: