// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/admin/admin.proto

package adminpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Make or delete admin
type MakeAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // his id in db
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeAdminRequest) Reset() {
	*x = MakeAdminRequest{}
	mi := &file_proto_admin_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeAdminRequest) ProtoMessage() {}

func (x *MakeAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeAdminRequest.ProtoReflect.Descriptor instead.
func (*MakeAdminRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_proto_rawDescGZIP(), []int{0}
}

func (x *MakeAdminRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type MakeAdminResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Response      string                 `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeAdminResponse) Reset() {
	*x = MakeAdminResponse{}
	mi := &file_proto_admin_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeAdminResponse) ProtoMessage() {}

func (x *MakeAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeAdminResponse.ProtoReflect.Descriptor instead.
func (*MakeAdminResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_proto_rawDescGZIP(), []int{1}
}

func (x *MakeAdminResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *MakeAdminResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

type DeleteAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAdminRequest) Reset() {
	*x = DeleteAdminRequest{}
	mi := &file_proto_admin_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAdminRequest) ProtoMessage() {}

func (x *DeleteAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAdminRequest.ProtoReflect.Descriptor instead.
func (*DeleteAdminRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteAdminRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteAdminResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Response      string                 `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAdminResponse) Reset() {
	*x = DeleteAdminResponse{}
	mi := &file_proto_admin_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAdminResponse) ProtoMessage() {}

func (x *DeleteAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAdminResponse.ProtoReflect.Descriptor instead.
func (*DeleteAdminResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteAdminResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *DeleteAdminResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

// Make employee
type MakeEmployeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeEmployeeRequest) Reset() {
	*x = MakeEmployeeRequest{}
	mi := &file_proto_admin_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeEmployeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeEmployeeRequest) ProtoMessage() {}

func (x *MakeEmployeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeEmployeeRequest.ProtoReflect.Descriptor instead.
func (*MakeEmployeeRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_proto_rawDescGZIP(), []int{4}
}

func (x *MakeEmployeeRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type MakeEmployeeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Response      string                 `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeEmployeeResponse) Reset() {
	*x = MakeEmployeeResponse{}
	mi := &file_proto_admin_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeEmployeeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeEmployeeResponse) ProtoMessage() {}

func (x *MakeEmployeeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeEmployeeResponse.ProtoReflect.Descriptor instead.
func (*MakeEmployeeResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_proto_rawDescGZIP(), []int{5}
}

func (x *MakeEmployeeResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *MakeEmployeeResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

var File_proto_admin_admin_proto protoreflect.FileDescriptor

const file_proto_admin_admin_proto_rawDesc = "" +
	"\n" +
	"\x17proto/admin/admin.proto\x12\x05admin\"\"\n" +
	"\x10MakeAdminRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"G\n" +
	"\x11MakeAdminResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x1a\n" +
	"\bresponse\x18\x02 \x01(\tR\bresponse\"$\n" +
	"\x12DeleteAdminRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"I\n" +
	"\x13DeleteAdminResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x1a\n" +
	"\bresponse\x18\x02 \x01(\tR\bresponse\"%\n" +
	"\x13MakeEmployeeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"J\n" +
	"\x14MakeEmployeeResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x1a\n" +
	"\bresponse\x18\x02 \x01(\tR\bresponse2\xdd\x01\n" +
	"\fAdminService\x12>\n" +
	"\tMakeAdmin\x12\x17.admin.MakeAdminRequest\x1a\x18.admin.MakeAdminResponse\x12D\n" +
	"\vDeleteAdmin\x12\x19.admin.DeleteAdminRequest\x1a\x1a.admin.DeleteAdminResponse\x12G\n" +
	"\fMakeEmployee\x12\x1a.admin.MakeEmployeeRequest\x1a\x1b.admin.MakeEmployeeResponseB\x1dZ\x1bdiploma/proto/admin;adminpbb\x06proto3"

var (
	file_proto_admin_admin_proto_rawDescOnce sync.Once
	file_proto_admin_admin_proto_rawDescData []byte
)

func file_proto_admin_admin_proto_rawDescGZIP() []byte {
	file_proto_admin_admin_proto_rawDescOnce.Do(func() {
		file_proto_admin_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_admin_admin_proto_rawDesc), len(file_proto_admin_admin_proto_rawDesc)))
	})
	return file_proto_admin_admin_proto_rawDescData
}

var file_proto_admin_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_admin_admin_proto_goTypes = []any{
	(*MakeAdminRequest)(nil),     // 0: admin.MakeAdminRequest
	(*MakeAdminResponse)(nil),    // 1: admin.MakeAdminResponse
	(*DeleteAdminRequest)(nil),   // 2: admin.DeleteAdminRequest
	(*DeleteAdminResponse)(nil),  // 3: admin.DeleteAdminResponse
	(*MakeEmployeeRequest)(nil),  // 4: admin.MakeEmployeeRequest
	(*MakeEmployeeResponse)(nil), // 5: admin.MakeEmployeeResponse
}
var file_proto_admin_admin_proto_depIdxs = []int32{
	0, // 0: admin.AdminService.MakeAdmin:input_type -> admin.MakeAdminRequest
	2, // 1: admin.AdminService.DeleteAdmin:input_type -> admin.DeleteAdminRequest
	4, // 2: admin.AdminService.MakeEmployee:input_type -> admin.MakeEmployeeRequest
	1, // 3: admin.AdminService.MakeAdmin:output_type -> admin.MakeAdminResponse
	3, // 4: admin.AdminService.DeleteAdmin:output_type -> admin.DeleteAdminResponse
	5, // 5: admin.AdminService.MakeEmployee:output_type -> admin.MakeEmployeeResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_admin_admin_proto_init() }
func file_proto_admin_admin_proto_init() {
	if File_proto_admin_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_admin_admin_proto_rawDesc), len(file_proto_admin_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_admin_admin_proto_goTypes,
		DependencyIndexes: file_proto_admin_admin_proto_depIdxs,
		MessageInfos:      file_proto_admin_admin_proto_msgTypes,
	}.Build()
	File_proto_admin_admin_proto = out.File
	file_proto_admin_admin_proto_goTypes = nil
	file_proto_admin_admin_proto_depIdxs = nil
}
